name: "Github pages build"

on:
  push:
    branches: master 
  pull_request:
    branches: master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install xvbf
        run: |
          sudo apt install xvfb

      - name: Install drawio-desktop
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v15.4.0/drawio-amd64-15.4.0.deb
          sudo dpkg --force-depends -i ./drawio-amd64-15.4.0.deb

      - name: generate pages
        run: |
          bash_script/doc_build.sh
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

       # Deploy to github pages if it's a push on master
      - name: Deploy to github pages
        if: ${{ env.GITHUB_REF == 'refs/heads/master'}}
        if: github.ref == 'refs/heads/master'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SKIP_EMPTY_COMMITS: true
          MESSAGE: "Build from {sha}: {msg}"

      - name: Upload as artefact
        if: ${{ env.GITHUB_REF != 'refs/heads/master'}}
        uses: actions/upload-artifact@v2
        with:
          path: docs

      # - name: Checkout gh-page
      #   run: |
      #     git add docs
      #     git stash
      #     git checkout gh-page --track origin/gh-page
      #     git pull origin
      #     git merge --squash --strategy-option=theirs --allow-unrelated-histories stash
      #     git add .
      #     git commit -m "generated files on `date +'%Y-%m-%d %H:%M:%S'`"
      #     git push origin/gh-page HEAD:gh-page

      # - name: Commit & Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     branch: gh-page
      #     message: Reformat Code
      #     author_name: Code Formatter
      #     author_email: sphynx.generate@esmartcontrol.com
      #     force: true

      # - name: Publish to gh-page
      #   run: |
      #     git add docs
      #     git stash
      #     git checkout gh-page --track origin/gh-page
      #     git pull
      #     git merge --squash --strategy-option=theirs --allow-unrelated-histories stash
      #     git add .
      #     git commit -m "generated files on `date +'%Y-%m-%d %H:%M:%S'`"
      #     git push origin -b gh-page





   # - name: Commit documentation change s
   #    run: |
   #      git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
   #      cp -r docs/_build/html/* gh-pages/
   #      cd gh-pages
   #      git config --local user.email "action@github.com"
   #      git config --local user.name "GitHub Action"
   #      git add .
   #      git commit -m "Update documentation" -a || true
   #      # The above command will fail if no changes were present, so we ignore
   #      # the return code.
   #  - name: Push changes
   #    uses: ad-m/github-push-action@master
   #    with:
   #      branch: gh-pages
   #      directory: gh-pages
   #      github_token: ${{ secrets.GITHUB_TOKEN }}
